/*
 * rtu_config_template.h
 *
 *  Created on: Oct 26, 2025
 *      Author: jakubczekaj
 */

#ifndef MODBUS_PORTS_STM32_RTU_CONFIG_TEMPLATE_H_
#define MODBUS_PORTS_STM32_RTU_CONFIG_TEMPLATE_H_

#define TASK_CUSTOM_EVENT_HANDLING false
#define TASK_FLAG_MODBUS_RTU_READ_READY 0x01
#define TASK_FLAG_MODBUS_RTU_EMIT_READY 0x02

#endif /* MODBUS_PORTS_STM32_RTU_CONFIG_TEMPLATE_H_ */
